import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Alert } from "flowbite-react";
import SearchBar from '../components/SearchBar';
import { useState, useEffect } from 'react';


export default function Home() {

  const [search, setSearch] = useState('');

  const sendQuery = (query) => {
    console.log("Fetch API", query) // Send to fastapi
  }

  const handleSearchonClick = () => {
      sendQuery(search);
  }

  const handleQueryOnChange = (queryValue) => {
      setSearch(queryValue)
  }

  const handleQueryOnEnter = (queryValue, selectedItem) => {
      // console.log("Query enter", selectedItem.text)
      sendQuery(selectedItem.text);
  }

  return (
    <>
      <Head>
        <title>MMSR APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container mx-auto">
          <h1 className="text-3xl font-bold mb-3">
            MMSR Project Team B
          </h1>
          <SearchBar 
            handleSearchonClick={handleSearchonClick} 
            handleQueryOnChange={handleQueryOnChange} 
            handleQueryOnEnter={handleQueryOnEnter}>
          </SearchBar>
         
         
        </div>
      </main>
    </>
  )
}
