import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Alert } from "flowbite-react";
import SearchBar from '../components/SearchBar';

export default function Home({allSongs}) {
  return (
    <>
      <Head>
        <title>MMSR APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container mx-auto">
          <h1 className="text-3xl font-bold mb-3">
            MMSR Project Team B
          </h1>
          <SearchBar></SearchBar>
         
         
        </div>
      </main>
    </>
  )
}
